# dist: precise
# 

# os:
#   - linux

language: php

php:
  - 7.2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

cache:
  directories:
    - node_modules
    - vendor

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE venom;'

before_script:
  - cp .env.travis .env
  # - sudo mysql -e 'CREATE DATABASE testing;'
  - composer self-update
  - composer install --no-interaction
  - npm install --save
  - npm run production
  # - mysql_upgrade --force -uroot
  # - mysql -e 'create database venom;'
  # - mysql -u root -e 'CREATE USER `venom`@`localhost` IDENTIFIED BY "password";'
  # - mysql -e 'GRANT ALL ON venom.* TO `venom`@`localhost`;'
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv
  - php artisan db:seed 

script:
  - vendor/bin/phpunit