language: php

php:
  - 7.2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

cache:
  directories:
    - node_modules
    - vendor

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE venom;'

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - npm install --save
  - npm run production
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv
  - php artisan db:seed 

script:
  - vendor/bin/phpunit